// resflt.h: BuildWizard generated preprocessor defines
//           for gxres.rc
//
// DO NOT EDIT THIS FILE !!!
//
// Include this file in gxstndrd.rc using the "Resource Includes"
// menu option (right click into resource tree item in VC 5.0)
//
// Example:

// Read-only symbol directives:
// #include "afxres.h"
// #include "gxresrc.h"
// #include "resflt.h"

// Compile time directives:
// #include "res\1stGrid.rc2"  // non-Microsoft Visual C++ edited resources
// #define _AFX_NO_OLE_RESOURCES
// #define _AFX_NO_TRACKER_RESOURCES
// #define _AFX_NO_PROPERTY_RESOURCES
// #include "afxres.rc"         // Standard components
// #include "afxprint.rc"       // printing/print preview resources
// #include "gxres.rc"

#ifndef _RESFLT_H_
#define _RESFLT_H_

// BuildWizard generated preprocessor defines

#ifndef _GX_FILTER_RESOURCES
#define _GX_FILTER_RESOURCES
#endif

#ifndef _GX_CHECKBOX_RESOURCES
#define _GX_CHECKBOX_RESOURCES
#endif

#ifndef _GX_RADIOBTN_RESOURCES
#define _GX_RADIOBTN_RESOURCES
#endif

#ifndef _GX_SELECTRANGE_RESOURCES
#define _GX_SELECTRANGE_RESOURCES
#endif

#ifndef _GX_RESIZECELL_RESOURCES
#define _GX_RESIZECELL_RESOURCES
#endif

#ifndef _GX_TABWND_RESOURCES
#define _GX_TABWND_RESOURCES
#endif

#ifndef _GX_IMOUSE_RESOURCES
#define _GX_IMOUSE_RESOURCES
#endif

#ifndef _GX_PROPERTYDIALOG_RESOURCES
#define _GX_PROPERTYDIALOG_RESOURCES
#endif

#ifndef _GX_STYLESHEET_RESOURCES
#define _GX_STYLESHEET_RESOURCES
#endif



#endif	// _RESFLT_H_
